FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# alias pour que "logiops360_back/..." pointe sur /app
RUN ln -s /app /app/logiops360_back
CMD ["python","full_pipeline.py"]
